name = "BulletsMaggots"
uuid = "5750bfad-98dc-4250-83e6-c97d76c5dcbe"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.0.1"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
julia = "1"
ProgressMeter = "1"